### ISSUE TITLE
pre-commit

### ISSUE THREAD

**Issue by callumrollo** [callumrollo/glidertest#33]
Some kind of pre-commit would be good to enforce code style, catch typos, errors etc.

**Comment by eleanorfrajka** [comment]
I'm using this as my `.pre-commit-config.yaml` in amocarray (below).

`black` for style, `codespell` for spelling, `pytest` and `ruff` for linting (which also sorts imports).  But I didn't quite get it to work as a pre-commit and stage, so I just run it, fix what I can, and then stage/commit separately.

```
repos:
  - repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
      - id: black
        language_version: python3
        files: \.(py|ipynb)$
        exclude: ^data/

  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.6  # Check for the latest version
    hooks:
      - id: codespell
        args: ["--ignore-words-list", "nd"]  # Optional: ignore some false positives

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: end-of-file-fixer
        files: \.(py|yaml|yml|ipynb)$
        exclude: ^data/
      - id: trailing-whitespace
        files: \.(py|yaml|yml|ipynb)$
        exclude: ^data/
      - id: check-yaml
        files: \.(yaml|yml)$
        exclude: ^data/
      - id: check-added-large-files

  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: pytest -q
        language: system
        types: [python]
        exclude: ^data/

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.3.0
    hooks:
      - id: ruff
        args: ["--fix", "--exit-zero"]
        exclude: ^data/
```
